language: ruby
rvm:
- 2.1
cache:
- bundler
gemfile: travisGemfile
install:
- bundle install
before_script:
- chmod +x deploy.sh
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
script: "./deploy.sh"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - HTML_FOLDER="./_site/"
  - GH_REF="tnantoka/tldr"
  - secure: "1ShIs/awWlnqw6p/VREg7UFSBaVH/IXVPoygcDsx/nw8PegPX7XnxpCAr+V43GJ06VvWzluzbpfCkHqKZvSnYc4D8NheYo55YSwa/KCaHC/saZufSlXPqgl5+Ak9hWPbVp0FUho4WlX2299SVvvsXGwKYLRTf4cvGEwYBM4LhstxMXJ3YyVbhRjxO5/v927ZsKa5bOZmry999h7nfjSfejGTzNdaRDAoVSJDp+I47dTFotFAmHvxLhO0bz/JyoAqP38Ti58yCoumpZEHGnUbSU/phS0izVuOFhTx3GsOnDwCUIxXcJIto9GnobqRdQkn2zroaOo3T4BGvKPEg/1M3rEbM1zUyV0gBW7aj4JJrOOXM+mrWB/qeMA7lb/pPLjkzEniQknBe1M3Z6llJXJtxuL/cBvp/29iPKn9zmuGih7ipzRsPmIkcIkNG37ozfMWKr6I3/t6YlrqX51bvf8gorV7autyKv/Nx9xYFoR0dwMfy2AK0RMiJv1cZk+6LKPDFkQcvRA3WnIzGJ8x0YJbwC/WQeyu1NafLc1tiH0IST1f0xHgDwKMjRSY9oRlvO3EsTo1kd+PAvRm8Yqc8jelkJhqE8D6FmB5Uqy1oO7li0tIN9qB51eai5qaDaT2na0RbRvtNerbzYfQWlYehzr6gggPISX8PyhPPES1k6/Qroc="
branches:
  only:
  - master
  - gh-pages
notifications:
  email: false
