
# SEO settings
title: "Too Long; Didn't Read"
description: "A free Jekyll theme for download"
keywords: "Jekyll, theme, free, download, SEO, blog, web"
url: http://tldr.tnantoka.com
baseurl: null

google_analytics: UA-78056002-1
repo: https://github.com/tnantoka/tldr
disqus_shortname: "tnantoka-tldr"

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 4
paginate_path: "/page/:num/"
comments: true

source: source
destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : tnantoka
  email    : tnantoka@bornneet.com
  url      : http://tnantoka.com
  github   : https://github.com/tnantoka
  twitter  : https://twitter.com/tnantoka

intro: "長文置き場"

# social settings
og_locale: "ja_JP"
twitter_site: "@tnantoka"

gems:
  - bourbon
  - jekyll-paginate

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
